### ISSUE TITLE
Current version doesn't disable c6 after resume from hibernate/suspend

### ISSUE THREAD

**Issue by schaueho** [jfredrickson/disable-c6#1]
When I put my machine to suspend or hibernate and resume the system afterwards, C6 states will be enabled, because systemctl will not re-run the disable-c6 service.

**Comment by schaueho** [comment]
The fix apparently is to add the suspend.target to the After option in the Unit configuration:

    -After=sysinit.target local-fs.target
    +After=sysinit.target local-fs.target suspend.target

**Comment by jfredrickson** [comment]
@schaueho Did you add this locally and did it work for you? I'm unable to test it myself.

**Comment by jfredrickson** [comment]
Fixed in #3. Thanks!
