### ISSUE TITLE
zenstates.py not included upon git cloning?

### ISSUE THREAD

**Issue by fyrak1s** [jfredrickson/disable-c6#4]
Upon doing:
`git clone https://github.com/jfredrickson/disable-c6.git`

The zenstates.py file is nowhere to be found.  The `disable-c6/lib/ZenStates-Linux/` directory is simply empty. Shouldn't it be in that folder?

**Comment by jfredrickson** [comment]
Ahh, the instructions are missing a step. Thanks for letting me know! I'll update the instructions.

After `git clone`, you'll need to also do:

```
git submodule init
git submodule update
```

This will pull the ZenStates files from that repo.
