### ISSUE TITLE
submodule update permission issue

### ISSUE THREAD

**Issue by sanket9918** [jfredrickson/disable-c6#6]
The command is not helpful as it is having a permission issue as stated directly in the terminal.

> sanket@sanket-Lenovo-ideapad-330-15ARR:~/disable-c6$ git submodule update
> Cloning into '/home/sanket/disable-c6/lib/ZenStates-Linux'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:r4m0n/ZenStates-Linux.git' into submodule path '/home/sanket/disable-c6/lib/ZenStates-Linux' failed
> Failed to clone 'lib/ZenStates-Linux'. Retry scheduled
> Cloning into '/home/sanket/disable-c6/lib/ZenStates-Linux'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:r4m0n/ZenStates-Linux.git' into submodule path '/home/sanket/disable-c6/lib/ZenStates-Linux' failed
> Failed to clone 'lib/ZenStates-Linux' a second time, aborting
>

**Comment by jfredrickson** [comment]
Please pull the latest code and give it a try again.

The submodule URL was using SSH, and you don't seem to have a SSH key configured in GitHub. I've updated it to use HTTPS instead so folks don't need to configure their GitHub account with a SSH key in order to check out the submodule.

**Comment by sanket9918** [comment]
Thank you for your kind response, the issue has been resolved and I think this is probably a good measure for now to prevent the soft lock in the Ryzen build.
